### ISSUE TITLE
What is the factorial of a negative number? 

### ISSUE THREAD

**Issue by Nahid-Hassan** [Zannatul-Naim/Programming_Languages#1]
https://github.com/Zannatul-Naim/Programming_Languages/blob/6fb27a7f1d7a0fe6c722c3c2b13d74d8f7ba4698/C/Basic/Factorial.c#L15

**Comment by Zannatul-Naim** [comment]
**Factorial is defined only for non-negative integer numbers.**
My code has an bug for this situation and I'm tried to solve this problem.
